project_id: "569905"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

# We generally want to use the "two-letters-code" of a locale (ie the language)
# But not for all locales!
# "pt-BR" may be better to remain as "pt-BR" instead of being transformed to "pt"
# Note: &/* is Yaml anchor syntax: https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/
languages_mapping: &languages_mapping
  two_letters_code:
    pt-BR: pt-BR

#
# Files configuration
#
files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
    languages_mapping: *languages_mapping
  # Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping: *languages_mapping
  # Blog Markdown files
  - source: /blog/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
    languages_mapping: *languages_mapping
